export const teaserHome = {
  status: "Ledger launch shell / April 2026",
  title: "Sharper CRE finance systems with operator-grade leverage.",
  description:
    "Cleaner models, tighter workflows, and lender-ready outputs built from live CRE accounting and finance operations.",
  primaryCta: {
    label: "See operating layer preview",
    href: "/home",
  },
  secondaryCta: {
    label: "Get launch notes",
    href: "/home#newsletter",
  },
  tertiaryRoute: {
    text: "Hiring or consulting conversations?",
    label: "View options",
    href: "/home#contact",
  },
  note: "Dark editorial branch active. Surfaces are staged as inspectable fragments.",
  proofPoints: [
    "70+ assets watched in one complex CRE operating stack",
    "$800M supported through finance and reporting operations",
    "20x cycle-time reduction from field-to-accounting workflow software",
  ],
  audienceRoutes: [
    {
      ref: "Route 01",
      label: "For operators",
      title: "See templates and workflow systems",
      detail: "Review launch surfaces for reporting templates, close-cycle workflows, and reusable prompt infrastructure.",
      href: "/home#launch",
      cta: "Explore operator lanes",
    },
    {
      ref: "Route 02",
      label: "For hiring managers",
      title: "Review proof of shipped operating systems",
      detail: "Jump to selected proof and evaluate system design, execution quality, and operator judgment.",
      href: "/home#work",
      cta: "Go to proof",
    },
    {
      ref: "Route 03",
      label: "For launch updates",
      title: "Get research notes and launch drops",
      detail: "Subscribe for release notes and operator memos as templates and tools move from preview to live.",
      href: "/home#newsletter",
      cta: "Get updates",
    },
  ],
  artifactHeader: "Preview surfaces / schematic view",
  artifactKicker: "Ledger atmosphere / controlled fragments / visible joins",
  artifactNodes: [
    "Reporting logic layer",
    "Debt stack visibility",
    "Variance and covenant checks",
    "Lender-facing outputs",
  ],
  spreadsheet: {
    label: "Template sheet / covenant controls",
    title: "Debt stack and covenant control",
    rows: [
      ["DSCR", "1.42x", "+0.08"],
      ["LTV", "58.4%", "-1.6%"],
      ["Rate cap", "Protected", "Active"],
      ["Cash sweep", "Off", "Stable"],
    ],
  },
  dashboard: {
    label: "Workflow signal / close clock",
    title: "Close-cycle pulse",
    metrics: [
      { label: "Assets watched", value: "72" },
      { label: "Variance flags", value: "06" },
      { label: "Close clock", value: "4.2d" },
    ],
  },
  memo: {
    label: "Operator memo / research lane",
    title: "Operator memo 02",
    lines: [
      "Leverage starts where reporting handoffs stop leaking context.",
      "The fix is tighter source models and fewer manual bridges.",
      "Prompts and automations should reinforce operator judgment, not replace it.",
    ],
  },
  lanes: [
    {
      kind: "template",
      label: "Templates",
      text: "Operator-grade Excel systems for debt, budgets, and recurring reporting logic.",
      detail: "Structured inputs, covenant checks, and audit-friendly output layers for lender and leadership reporting.",
      surfaceLabel: "Artifact class / model sheet",
      href: "/projects#templates",
      cta: "View template lane",
    },
    {
      kind: "workflow",
      label: "Workflows",
      text: "AI-assisted workflows for document extraction, close support, and reporting throughput.",
      detail: "Routed states, owner handoffs, and exception paths tuned to reduce close-cycle drag.",
      surfaceLabel: "Artifact class / routed process",
      href: "/projects",
      cta: "View workflow lane",
    },
    {
      kind: "research",
      label: "Research",
      text: "Tight operator memos on CRE finance systems, controls, and practical automation.",
      detail: "Short, specific notes for teams that want cleaner reporting logic and sharper operating judgment.",
      surfaceLabel: "Artifact class / operator memo",
      href: "/home#research",
      cta: "Read research lane",
    },
  ],
  footer: {
    lead: "Built for CRE operators, finance leaders, and teams hiring for systems-level execution.",
    contactLabel: "Email for direct conversation",
    contactValue: "melanson633@gmail.com",
  },
};
